--=========================================================================
-- CyberTheatre
--=========================================================================


---------------------------------------------------------------------------
-- Prolog for sqlite
---------------------------------------------------------------------------

PRAGMA foreign_keys = ON;

---------------------------------------------------------------------------
-- LesSpectacles
---------------------------------------------------------------------------

INSERT INTO LesSpectacles (nomSpectacle) VALUES ('1','Phantom of the Opera');
INSERT INTO LesSpectacles (nomSpectacle) VALUES ('2','Les Miserable');
INSERT INTO LesSpectacles (nomSpectacle) VALUES ('3','Le Lac des Cygnes');
INSERT INTO LesSpectacles (nomSpectacle) VALUES ('4','A streetcar named Desire');
INSERT INTO LesSpectacles (nomSpectacle) VALUES ('5','Phantom of the Opera');
INSERT INTO LesSpectacles (nomSpectacle) VALUES ('6','Cats');

---------------------------------------------------------------------------
-- LesZones
---------------------------------------------------------------------------

INSERT INTO LesZones VALUES ('1', 'Galeries', '100', '10');
INSERT INTO LesZones VALUES ('2', 'Fond','100', '15');
INSERT INTO LesZones VALUES ('3', 'Distincts','100', '20');
INSERT INTO LesZones VALUES ('4', 'Parterre','100', '30');
INSERT INTO LesZones VALUES ('5', 'Balcons','100', '50');

---------------------------------------------------------------------------
-- LesPlaces
---------------------------------------------------------------------------

INSERT INTO LesPlaces VALUES ('1', '1', '1');
INSERT INTO LesPlaces VALUES ('1', '1', '2');
INSERT INTO LesPlaces VALUES ('1', '1', '3');
INSERT INTO LesPlaces VALUES ('1', '1', '4');
INSERT INTO LesPlaces VALUES ('1', '1', '5');
INSERT INTO LesPlaces VALUES ('2', '1', '1');
INSERT INTO LesPlaces VALUES ('2', '1', '2');
INSERT INTO LesPlaces VALUES ('2', '1', '3');
INSERT INTO LesPlaces VALUES ('2', '1', '4');
INSERT INTO LesPlaces VALUES ('2', '1', '5');
INSERT INTO LesPlaces VALUES ('3', '1', '1');
INSERT INTO LesPlaces VALUES ('3', '1', '2');
INSERT INTO LesPlaces VALUES ('3', '1', '3');
INSERT INTO LesPlaces VALUES ('3', '1', '4');
INSERT INTO LesPlaces VALUES ('3', '1', '5');
INSERT INTO LesPlaces VALUES ('4', '1', '1');
INSERT INTO LesPlaces VALUES ('4', '1', '2');
INSERT INTO LesPlaces VALUES ('4', '1', '3');
INSERT INTO LesPlaces VALUES ('4', '1', '4');
INSERT INTO LesPlaces VALUES ('4', '1', '5');
INSERT INTO LesPlaces VALUES ('5', '1', '1');
INSERT INTO LesPlaces VALUES ('5', '1', '2');
INSERT INTO LesPlaces VALUES ('5', '1', '3');
INSERT INTO LesPlaces VALUES ('5', '1', '4');
INSERT INTO LesPlaces VALUES ('5', '1', '5');
INSERT INTO LesPlaces VALUES ('6', '1', '1');
INSERT INTO LesPlaces VALUES ('6', '1', '2');
INSERT INTO LesPlaces VALUES ('6', '1', '3');
INSERT INTO LesPlaces VALUES ('6', '1', '4');
INSERT INTO LesPlaces VALUES ('6', '1', '5');
INSERT INTO LesPlaces VALUES ('7', '1', '1');
INSERT INTO LesPlaces VALUES ('7', '1', '2');
INSERT INTO LesPlaces VALUES ('7', '1', '3');
INSERT INTO LesPlaces VALUES ('7', '1', '4');
INSERT INTO LesPlaces VALUES ('7', '1', '5');
INSERT INTO LesPlaces VALUES ('8', '1', '1');
INSERT INTO LesPlaces VALUES ('8', '1', '2');
INSERT INTO LesPlaces VALUES ('8', '1', '3');
INSERT INTO LesPlaces VALUES ('8', '1', '4');
INSERT INTO LesPlaces VALUES ('8', '1', '5');
INSERT INTO LesPlaces VALUES ('9', '1', '1');
INSERT INTO LesPlaces VALUES ('9', '1', '2');
INSERT INTO LesPlaces VALUES ('9', '1', '3');
INSERT INTO LesPlaces VALUES ('9', '1', '4');
INSERT INTO LesPlaces VALUES ('9', '1', '5');
INSERT INTO LesPlaces VALUES ('10', '1', '1');
INSERT INTO LesPlaces VALUES ('10', '1', '2');
INSERT INTO LesPlaces VALUES ('10', '1', '3');
INSERT INTO LesPlaces VALUES ('10', '1', '4');
INSERT INTO LesPlaces VALUES ('10', '1', '5');
INSERT INTO LesPlaces VALUES ('11', '1', '1');
INSERT INTO LesPlaces VALUES ('11', '1', '2');
INSERT INTO LesPlaces VALUES ('11', '1', '3');
INSERT INTO LesPlaces VALUES ('11', '1', '4');
INSERT INTO LesPlaces VALUES ('11', '1', '5');
INSERT INTO LesPlaces VALUES ('12', '1', '1');
INSERT INTO LesPlaces VALUES ('12', '1', '2');
INSERT INTO LesPlaces VALUES ('12', '1', '3');
INSERT INTO LesPlaces VALUES ('12', '1', '4');
INSERT INTO LesPlaces VALUES ('12', '1', '5');
INSERT INTO LesPlaces VALUES ('13', '1', '1');
INSERT INTO LesPlaces VALUES ('13', '1', '2');
INSERT INTO LesPlaces VALUES ('13', '1', '3');
INSERT INTO LesPlaces VALUES ('13', '1', '4');
INSERT INTO LesPlaces VALUES ('13', '1', '5');
INSERT INTO LesPlaces VALUES ('14', '1', '1');
INSERT INTO LesPlaces VALUES ('14', '1', '2');
INSERT INTO LesPlaces VALUES ('14', '1', '3');
INSERT INTO LesPlaces VALUES ('14', '1', '4');
INSERT INTO LesPlaces VALUES ('14', '1', '5');
INSERT INTO LesPlaces VALUES ('15', '1', '1');
INSERT INTO LesPlaces VALUES ('15', '1', '2');
INSERT INTO LesPlaces VALUES ('15', '1', '3');
INSERT INTO LesPlaces VALUES ('15', '1', '4');
INSERT INTO LesPlaces VALUES ('15', '1', '5');
INSERT INTO LesPlaces VALUES ('16', '1', '1');
INSERT INTO LesPlaces VALUES ('16', '1', '2');
INSERT INTO LesPlaces VALUES ('16', '1', '3');
INSERT INTO LesPlaces VALUES ('16', '1', '4');
INSERT INTO LesPlaces VALUES ('16', '1', '5');
INSERT INTO LesPlaces VALUES ('17', '1', '1');
INSERT INTO LesPlaces VALUES ('17', '1', '2');
INSERT INTO LesPlaces VALUES ('17', '1', '3');
INSERT INTO LesPlaces VALUES ('17', '1', '4');
INSERT INTO LesPlaces VALUES ('17', '1', '5');
INSERT INTO LesPlaces VALUES ('18', '1', '1');
INSERT INTO LesPlaces VALUES ('18', '1', '2');
INSERT INTO LesPlaces VALUES ('18', '1', '3');
INSERT INTO LesPlaces VALUES ('18', '1', '4');
INSERT INTO LesPlaces VALUES ('18', '1', '5');
INSERT INTO LesPlaces VALUES ('19', '1', '1');
INSERT INTO LesPlaces VALUES ('19', '1', '2');
INSERT INTO LesPlaces VALUES ('19', '1', '3');
INSERT INTO LesPlaces VALUES ('19', '1', '4');
INSERT INTO LesPlaces VALUES ('19', '1', '5');
INSERT INTO LesPlaces VALUES ('20', '2', '1');
INSERT INTO LesPlaces VALUES ('20', '2', '2');
INSERT INTO LesPlaces VALUES ('20', '2', '3');
INSERT INTO LesPlaces VALUES ('20', '2', '4');
INSERT INTO LesPlaces VALUES ('20', '2', '5');
INSERT INTO LesPlaces VALUES ('21', '2', '1');
INSERT INTO LesPlaces VALUES ('21', '2', '2');
INSERT INTO LesPlaces VALUES ('21', '2', '3');
INSERT INTO LesPlaces VALUES ('21', '2', '4');
INSERT INTO LesPlaces VALUES ('21', '2', '5');
INSERT INTO LesPlaces VALUES ('22', '2', '1');
INSERT INTO LesPlaces VALUES ('22', '2', '2');
INSERT INTO LesPlaces VALUES ('22', '2', '3');
INSERT INTO LesPlaces VALUES ('22', '2', '4');
INSERT INTO LesPlaces VALUES ('22', '2', '5');
INSERT INTO LesPlaces VALUES ('23', '2', '1');
INSERT INTO LesPlaces VALUES ('23', '2', '2');
INSERT INTO LesPlaces VALUES ('23', '2', '3');
INSERT INTO LesPlaces VALUES ('23', '2', '4');
INSERT INTO LesPlaces VALUES ('23', '2', '5');
INSERT INTO LesPlaces VALUES ('24', '2', '1');
INSERT INTO LesPlaces VALUES ('24', '2', '2');
INSERT INTO LesPlaces VALUES ('24', '2', '3');
INSERT INTO LesPlaces VALUES ('24', '2', '4');
INSERT INTO LesPlaces VALUES ('24', '2', '5');
INSERT INTO LesPlaces VALUES ('25', '2', '1');
INSERT INTO LesPlaces VALUES ('25', '2', '2');
INSERT INTO LesPlaces VALUES ('25', '2', '3');
INSERT INTO LesPlaces VALUES ('25', '2', '4');
INSERT INTO LesPlaces VALUES ('25', '2', '5');
INSERT INTO LesPlaces VALUES ('26', '2', '1');
INSERT INTO LesPlaces VALUES ('26', '2', '2');
INSERT INTO LesPlaces VALUES ('26', '2', '3');
INSERT INTO LesPlaces VALUES ('26', '2', '4');
INSERT INTO LesPlaces VALUES ('26', '2', '5');
INSERT INTO LesPlaces VALUES ('27', '2', '1');
INSERT INTO LesPlaces VALUES ('27', '2', '2');
INSERT INTO LesPlaces VALUES ('27', '2', '3');
INSERT INTO LesPlaces VALUES ('27', '2', '4');
INSERT INTO LesPlaces VALUES ('27', '2', '5');
INSERT INTO LesPlaces VALUES ('28', '2', '1');
INSERT INTO LesPlaces VALUES ('28', '2', '2');
INSERT INTO LesPlaces VALUES ('28', '2', '3');
INSERT INTO LesPlaces VALUES ('28', '2', '4');
INSERT INTO LesPlaces VALUES ('28', '2', '5');
INSERT INTO LesPlaces VALUES ('29', '2', '1');
INSERT INTO LesPlaces VALUES ('29', '2', '2');
INSERT INTO LesPlaces VALUES ('29', '2', '3');
INSERT INTO LesPlaces VALUES ('29', '2', '4');
INSERT INTO LesPlaces VALUES ('29', '2', '5');
INSERT INTO LesPlaces VALUES ('30', '2', '1');
INSERT INTO LesPlaces VALUES ('30', '2', '2');
INSERT INTO LesPlaces VALUES ('30', '2', '3');
INSERT INTO LesPlaces VALUES ('30', '2', '4');
INSERT INTO LesPlaces VALUES ('30', '2', '5');
INSERT INTO LesPlaces VALUES ('31', '2', '1');
INSERT INTO LesPlaces VALUES ('31', '2', '2');
INSERT INTO LesPlaces VALUES ('31', '2', '3');
INSERT INTO LesPlaces VALUES ('31', '2', '4');
INSERT INTO LesPlaces VALUES ('31', '2', '5');
INSERT INTO LesPlaces VALUES ('32', '2', '1');
INSERT INTO LesPlaces VALUES ('32', '2', '2');
INSERT INTO LesPlaces VALUES ('32', '2', '3');
INSERT INTO LesPlaces VALUES ('32', '2', '4');
INSERT INTO LesPlaces VALUES ('32', '2', '5');
INSERT INTO LesPlaces VALUES ('33', '2', '1');
INSERT INTO LesPlaces VALUES ('33', '2', '2');
INSERT INTO LesPlaces VALUES ('33', '2', '3');
INSERT INTO LesPlaces VALUES ('33', '2', '4');
INSERT INTO LesPlaces VALUES ('33', '2', '5');
INSERT INTO LesPlaces VALUES ('34', '2', '1');
INSERT INTO LesPlaces VALUES ('34', '2', '2');
INSERT INTO LesPlaces VALUES ('34', '2', '3');
INSERT INTO LesPlaces VALUES ('34', '2', '4');
INSERT INTO LesPlaces VALUES ('34', '2', '5');
INSERT INTO LesPlaces VALUES ('35', '2', '1');
INSERT INTO LesPlaces VALUES ('35', '2', '2');
INSERT INTO LesPlaces VALUES ('35', '2', '3');
INSERT INTO LesPlaces VALUES ('35', '2', '4');
INSERT INTO LesPlaces VALUES ('35', '2', '5');
INSERT INTO LesPlaces VALUES ('36', '2', '1');
INSERT INTO LesPlaces VALUES ('36', '2', '2');
INSERT INTO LesPlaces VALUES ('36', '2', '3');
INSERT INTO LesPlaces VALUES ('36', '2', '4');
INSERT INTO LesPlaces VALUES ('36', '2', '5');
INSERT INTO LesPlaces VALUES ('37', '2', '1');
INSERT INTO LesPlaces VALUES ('37', '2', '2');
INSERT INTO LesPlaces VALUES ('37', '2', '3');
INSERT INTO LesPlaces VALUES ('37', '2', '4');
INSERT INTO LesPlaces VALUES ('37', '2', '5');
INSERT INTO LesPlaces VALUES ('38', '2', '1');
INSERT INTO LesPlaces VALUES ('38', '2', '2');
INSERT INTO LesPlaces VALUES ('38', '2', '3');
INSERT INTO LesPlaces VALUES ('38', '2', '4');
INSERT INTO LesPlaces VALUES ('38', '2', '5');
INSERT INTO LesPlaces VALUES ('39', '2', '1');
INSERT INTO LesPlaces VALUES ('39', '2', '2');
INSERT INTO LesPlaces VALUES ('39', '2', '3');
INSERT INTO LesPlaces VALUES ('39', '2', '4');
INSERT INTO LesPlaces VALUES ('39', '2', '5');
INSERT INTO LesPlaces VALUES ('40', '3', '1');
INSERT INTO LesPlaces VALUES ('40', '3', '2');
INSERT INTO LesPlaces VALUES ('40', '3', '3');
INSERT INTO LesPlaces VALUES ('40', '3', '4');
INSERT INTO LesPlaces VALUES ('40', '3', '5');
INSERT INTO LesPlaces VALUES ('41', '3', '1');
INSERT INTO LesPlaces VALUES ('41', '3', '2');
INSERT INTO LesPlaces VALUES ('41', '3', '3');
INSERT INTO LesPlaces VALUES ('41', '3', '4');
INSERT INTO LesPlaces VALUES ('41', '3', '5');
INSERT INTO LesPlaces VALUES ('42', '3', '1');
INSERT INTO LesPlaces VALUES ('42', '3', '2');
INSERT INTO LesPlaces VALUES ('42', '3', '3');
INSERT INTO LesPlaces VALUES ('42', '3', '4');
INSERT INTO LesPlaces VALUES ('42', '3', '5');
INSERT INTO LesPlaces VALUES ('43', '3', '1');
INSERT INTO LesPlaces VALUES ('43', '3', '2');
INSERT INTO LesPlaces VALUES ('43', '3', '3');
INSERT INTO LesPlaces VALUES ('43', '3', '4');
INSERT INTO LesPlaces VALUES ('43', '3', '5');
INSERT INTO LesPlaces VALUES ('44', '3', '1');
INSERT INTO LesPlaces VALUES ('44', '3', '2');
INSERT INTO LesPlaces VALUES ('44', '3', '3');
INSERT INTO LesPlaces VALUES ('44', '3', '4');
INSERT INTO LesPlaces VALUES ('44', '3', '5');
INSERT INTO LesPlaces VALUES ('45', '3', '1');
INSERT INTO LesPlaces VALUES ('45', '3', '2');
INSERT INTO LesPlaces VALUES ('45', '3', '3');
INSERT INTO LesPlaces VALUES ('45', '3', '4');
INSERT INTO LesPlaces VALUES ('45', '3', '5');
INSERT INTO LesPlaces VALUES ('46', '3', '1');
INSERT INTO LesPlaces VALUES ('46', '3', '2');
INSERT INTO LesPlaces VALUES ('46', '3', '3');
INSERT INTO LesPlaces VALUES ('46', '3', '4');
INSERT INTO LesPlaces VALUES ('46', '3', '5');
INSERT INTO LesPlaces VALUES ('47', '3', '1');
INSERT INTO LesPlaces VALUES ('47', '3', '2');
INSERT INTO LesPlaces VALUES ('47', '3', '3');
INSERT INTO LesPlaces VALUES ('47', '3', '4');
INSERT INTO LesPlaces VALUES ('47', '3', '5');
INSERT INTO LesPlaces VALUES ('48', '3', '1');
INSERT INTO LesPlaces VALUES ('48', '3', '2');
INSERT INTO LesPlaces VALUES ('48', '3', '3');
INSERT INTO LesPlaces VALUES ('48', '3', '4');
INSERT INTO LesPlaces VALUES ('48', '3', '5');
INSERT INTO LesPlaces VALUES ('49', '3', '1');
INSERT INTO LesPlaces VALUES ('49', '3', '2');
INSERT INTO LesPlaces VALUES ('49', '3', '3');
INSERT INTO LesPlaces VALUES ('49', '3', '4');
INSERT INTO LesPlaces VALUES ('49', '3', '5');
INSERT INTO LesPlaces VALUES ('50', '3', '1');
INSERT INTO LesPlaces VALUES ('50', '3', '2');
INSERT INTO LesPlaces VALUES ('50', '3', '3');
INSERT INTO LesPlaces VALUES ('50', '3', '4');
INSERT INTO LesPlaces VALUES ('50', '3', '5');
INSERT INTO LesPlaces VALUES ('51', '3', '1');
INSERT INTO LesPlaces VALUES ('51', '3', '2');
INSERT INTO LesPlaces VALUES ('51', '3', '3');
INSERT INTO LesPlaces VALUES ('51', '3', '4');
INSERT INTO LesPlaces VALUES ('51', '3', '5');
INSERT INTO LesPlaces VALUES ('52', '3', '1');
INSERT INTO LesPlaces VALUES ('52', '3', '2');
INSERT INTO LesPlaces VALUES ('52', '3', '3');
INSERT INTO LesPlaces VALUES ('52', '3', '4');
INSERT INTO LesPlaces VALUES ('52', '3', '5');
INSERT INTO LesPlaces VALUES ('53', '3', '1');
INSERT INTO LesPlaces VALUES ('53', '3', '2');
INSERT INTO LesPlaces VALUES ('53', '3', '3');
INSERT INTO LesPlaces VALUES ('53', '3', '4');
INSERT INTO LesPlaces VALUES ('53', '3', '5');
INSERT INTO LesPlaces VALUES ('54', '3', '1');
INSERT INTO LesPlaces VALUES ('54', '3', '2');
INSERT INTO LesPlaces VALUES ('54', '3', '3');
INSERT INTO LesPlaces VALUES ('54', '3', '4');
INSERT INTO LesPlaces VALUES ('54', '3', '5');
INSERT INTO LesPlaces VALUES ('55', '3', '1');
INSERT INTO LesPlaces VALUES ('55', '3', '2');
INSERT INTO LesPlaces VALUES ('55', '3', '3');
INSERT INTO LesPlaces VALUES ('55', '3', '4');
INSERT INTO LesPlaces VALUES ('55', '3', '5');
INSERT INTO LesPlaces VALUES ('56', '3', '1');
INSERT INTO LesPlaces VALUES ('56', '3', '2');
INSERT INTO LesPlaces VALUES ('56', '3', '3');
INSERT INTO LesPlaces VALUES ('56', '3', '4');
INSERT INTO LesPlaces VALUES ('56', '3', '5');
INSERT INTO LesPlaces VALUES ('57', '3', '1');
INSERT INTO LesPlaces VALUES ('57', '3', '2');
INSERT INTO LesPlaces VALUES ('57', '3', '3');
INSERT INTO LesPlaces VALUES ('57', '3', '4');
INSERT INTO LesPlaces VALUES ('57', '3', '5');
INSERT INTO LesPlaces VALUES ('58', '3', '1');
INSERT INTO LesPlaces VALUES ('58', '3', '2');
INSERT INTO LesPlaces VALUES ('58', '3', '3');
INSERT INTO LesPlaces VALUES ('58', '3', '4');
INSERT INTO LesPlaces VALUES ('58', '3', '5');
INSERT INTO LesPlaces VALUES ('59', '3', '1');
INSERT INTO LesPlaces VALUES ('59', '3', '2');
INSERT INTO LesPlaces VALUES ('59', '3', '3');
INSERT INTO LesPlaces VALUES ('59', '3', '4');
INSERT INTO LesPlaces VALUES ('59', '3', '5');
INSERT INTO LesPlaces VALUES ('60', '4', '1');
INSERT INTO LesPlaces VALUES ('60', '4', '2');
INSERT INTO LesPlaces VALUES ('60', '4', '3');
INSERT INTO LesPlaces VALUES ('60', '4', '4');
INSERT INTO LesPlaces VALUES ('60', '4', '5');
INSERT INTO LesPlaces VALUES ('61', '4', '1');
INSERT INTO LesPlaces VALUES ('61', '4', '2');
INSERT INTO LesPlaces VALUES ('61', '4', '3');
INSERT INTO LesPlaces VALUES ('61', '4', '4');
INSERT INTO LesPlaces VALUES ('61', '4', '5');
INSERT INTO LesPlaces VALUES ('62', '4', '1');
INSERT INTO LesPlaces VALUES ('62', '4', '2');
INSERT INTO LesPlaces VALUES ('62', '4', '3');
INSERT INTO LesPlaces VALUES ('62', '4', '4');
INSERT INTO LesPlaces VALUES ('62', '4', '5');
INSERT INTO LesPlaces VALUES ('63', '4', '1');
INSERT INTO LesPlaces VALUES ('63', '4', '2');
INSERT INTO LesPlaces VALUES ('63', '4', '3');
INSERT INTO LesPlaces VALUES ('63', '4', '4');
INSERT INTO LesPlaces VALUES ('63', '4', '5');
INSERT INTO LesPlaces VALUES ('64', '4', '1');
INSERT INTO LesPlaces VALUES ('64', '4', '2');
INSERT INTO LesPlaces VALUES ('64', '4', '3');
INSERT INTO LesPlaces VALUES ('64', '4', '4');
INSERT INTO LesPlaces VALUES ('64', '4', '5');
INSERT INTO LesPlaces VALUES ('65', '4', '1');
INSERT INTO LesPlaces VALUES ('65', '4', '2');
INSERT INTO LesPlaces VALUES ('65', '4', '3');
INSERT INTO LesPlaces VALUES ('65', '4', '4');
INSERT INTO LesPlaces VALUES ('65', '4', '5');
INSERT INTO LesPlaces VALUES ('66', '4', '1');
INSERT INTO LesPlaces VALUES ('66', '4', '2');
INSERT INTO LesPlaces VALUES ('66', '4', '3');
INSERT INTO LesPlaces VALUES ('66', '4', '4');
INSERT INTO LesPlaces VALUES ('66', '4', '5');
INSERT INTO LesPlaces VALUES ('67', '4', '1');
INSERT INTO LesPlaces VALUES ('67', '4', '2');
INSERT INTO LesPlaces VALUES ('67', '4', '3');
INSERT INTO LesPlaces VALUES ('67', '4', '4');
INSERT INTO LesPlaces VALUES ('67', '4', '5');
INSERT INTO LesPlaces VALUES ('68', '4', '1');
INSERT INTO LesPlaces VALUES ('68', '4', '2');
INSERT INTO LesPlaces VALUES ('68', '4', '3');
INSERT INTO LesPlaces VALUES ('68', '4', '4');
INSERT INTO LesPlaces VALUES ('68', '4', '5');
INSERT INTO LesPlaces VALUES ('69', '4', '1');
INSERT INTO LesPlaces VALUES ('69', '4', '2');
INSERT INTO LesPlaces VALUES ('69', '4', '3');
INSERT INTO LesPlaces VALUES ('69', '4', '4');
INSERT INTO LesPlaces VALUES ('69', '4', '5');
INSERT INTO LesPlaces VALUES ('70', '4', '1');
INSERT INTO LesPlaces VALUES ('70', '4', '2');
INSERT INTO LesPlaces VALUES ('70', '4', '3');
INSERT INTO LesPlaces VALUES ('70', '4', '4');
INSERT INTO LesPlaces VALUES ('70', '4', '5');
INSERT INTO LesPlaces VALUES ('71', '4', '1');
INSERT INTO LesPlaces VALUES ('71', '4', '2');
INSERT INTO LesPlaces VALUES ('71', '4', '3');
INSERT INTO LesPlaces VALUES ('71', '4', '4');
INSERT INTO LesPlaces VALUES ('71', '4', '5');
INSERT INTO LesPlaces VALUES ('72', '4', '1');
INSERT INTO LesPlaces VALUES ('72', '4', '2');
INSERT INTO LesPlaces VALUES ('72', '4', '3');
INSERT INTO LesPlaces VALUES ('72', '4', '4');
INSERT INTO LesPlaces VALUES ('72', '4', '5');
INSERT INTO LesPlaces VALUES ('73', '4', '1');
INSERT INTO LesPlaces VALUES ('73', '4', '2');
INSERT INTO LesPlaces VALUES ('73', '4', '3');
INSERT INTO LesPlaces VALUES ('73', '4', '4');
INSERT INTO LesPlaces VALUES ('73', '4', '5');
INSERT INTO LesPlaces VALUES ('74', '4', '1');
INSERT INTO LesPlaces VALUES ('74', '4', '2');
INSERT INTO LesPlaces VALUES ('74', '4', '3');
INSERT INTO LesPlaces VALUES ('74', '4', '4');
INSERT INTO LesPlaces VALUES ('74', '4', '5');
INSERT INTO LesPlaces VALUES ('75', '4', '1');
INSERT INTO LesPlaces VALUES ('75', '4', '2');
INSERT INTO LesPlaces VALUES ('75', '4', '3');
INSERT INTO LesPlaces VALUES ('75', '4', '4');
INSERT INTO LesPlaces VALUES ('75', '4', '5');
INSERT INTO LesPlaces VALUES ('76', '4', '1');
INSERT INTO LesPlaces VALUES ('76', '4', '2');
INSERT INTO LesPlaces VALUES ('76', '4', '3');
INSERT INTO LesPlaces VALUES ('76', '4', '4');
INSERT INTO LesPlaces VALUES ('76', '4', '5');
INSERT INTO LesPlaces VALUES ('77', '4', '1');
INSERT INTO LesPlaces VALUES ('77', '4', '2');
INSERT INTO LesPlaces VALUES ('77', '4', '3');
INSERT INTO LesPlaces VALUES ('77', '4', '4');
INSERT INTO LesPlaces VALUES ('77', '4', '5');
INSERT INTO LesPlaces VALUES ('78', '4', '1');
INSERT INTO LesPlaces VALUES ('78', '4', '2');
INSERT INTO LesPlaces VALUES ('78', '4', '3');
INSERT INTO LesPlaces VALUES ('78', '4', '4');
INSERT INTO LesPlaces VALUES ('78', '4', '5');
INSERT INTO LesPlaces VALUES ('79', '4', '1');
INSERT INTO LesPlaces VALUES ('79', '4', '2');
INSERT INTO LesPlaces VALUES ('79', '4', '3');
INSERT INTO LesPlaces VALUES ('79', '4', '4');
INSERT INTO LesPlaces VALUES ('79', '4', '5');
INSERT INTO LesPlaces VALUES ('80', '5', '1');
INSERT INTO LesPlaces VALUES ('80', '5', '2');
INSERT INTO LesPlaces VALUES ('80', '5', '3');
INSERT INTO LesPlaces VALUES ('80', '5', '4');
INSERT INTO LesPlaces VALUES ('80', '5', '5');
INSERT INTO LesPlaces VALUES ('81', '5', '1');
INSERT INTO LesPlaces VALUES ('81', '5', '2');
INSERT INTO LesPlaces VALUES ('81', '5', '3');
INSERT INTO LesPlaces VALUES ('81', '5', '4');
INSERT INTO LesPlaces VALUES ('81', '5', '5');
INSERT INTO LesPlaces VALUES ('82', '5', '1');
INSERT INTO LesPlaces VALUES ('82', '5', '2');
INSERT INTO LesPlaces VALUES ('82', '5', '3');
INSERT INTO LesPlaces VALUES ('82', '5', '4');
INSERT INTO LesPlaces VALUES ('82', '5', '5');
INSERT INTO LesPlaces VALUES ('83', '5', '1');
INSERT INTO LesPlaces VALUES ('83', '5', '2');
INSERT INTO LesPlaces VALUES ('83', '5', '3');
INSERT INTO LesPlaces VALUES ('83', '5', '4');
INSERT INTO LesPlaces VALUES ('83', '5', '5');
INSERT INTO LesPlaces VALUES ('84', '5', '1');
INSERT INTO LesPlaces VALUES ('84', '5', '2');
INSERT INTO LesPlaces VALUES ('84', '5', '3');
INSERT INTO LesPlaces VALUES ('84', '5', '4');
INSERT INTO LesPlaces VALUES ('84', '5', '5');
INSERT INTO LesPlaces VALUES ('85', '5', '1');
INSERT INTO LesPlaces VALUES ('85', '5', '2');
INSERT INTO LesPlaces VALUES ('85', '5', '3');
INSERT INTO LesPlaces VALUES ('85', '5', '4');
INSERT INTO LesPlaces VALUES ('85', '5', '5');
INSERT INTO LesPlaces VALUES ('86', '5', '1');
INSERT INTO LesPlaces VALUES ('86', '5', '2');
INSERT INTO LesPlaces VALUES ('86', '5', '3');
INSERT INTO LesPlaces VALUES ('86', '5', '4');
INSERT INTO LesPlaces VALUES ('86', '5', '5');
INSERT INTO LesPlaces VALUES ('87', '5', '1');
INSERT INTO LesPlaces VALUES ('87', '5', '2');
INSERT INTO LesPlaces VALUES ('87', '5', '3');
INSERT INTO LesPlaces VALUES ('87', '5', '4');
INSERT INTO LesPlaces VALUES ('87', '5', '5');
INSERT INTO LesPlaces VALUES ('88', '5', '1');
INSERT INTO LesPlaces VALUES ('88', '5', '2');
INSERT INTO LesPlaces VALUES ('88', '5', '3');
INSERT INTO LesPlaces VALUES ('88', '5', '4');
INSERT INTO LesPlaces VALUES ('88', '5', '5');
INSERT INTO LesPlaces VALUES ('89', '5', '1');
INSERT INTO LesPlaces VALUES ('89', '5', '2');
INSERT INTO LesPlaces VALUES ('89', '5', '3');
INSERT INTO LesPlaces VALUES ('89', '5', '4');
INSERT INTO LesPlaces VALUES ('89', '5', '5');
INSERT INTO LesPlaces VALUES ('90', '5', '1');
INSERT INTO LesPlaces VALUES ('90', '5', '2');
INSERT INTO LesPlaces VALUES ('90', '5', '3');
INSERT INTO LesPlaces VALUES ('90', '5', '4');
INSERT INTO LesPlaces VALUES ('90', '5', '5');
INSERT INTO LesPlaces VALUES ('91', '5', '1');
INSERT INTO LesPlaces VALUES ('91', '5', '2');
INSERT INTO LesPlaces VALUES ('91', '5', '3');
INSERT INTO LesPlaces VALUES ('91', '5', '4');
INSERT INTO LesPlaces VALUES ('91', '5', '5');
INSERT INTO LesPlaces VALUES ('92', '5', '1');
INSERT INTO LesPlaces VALUES ('92', '5', '2');
INSERT INTO LesPlaces VALUES ('92', '5', '3');
INSERT INTO LesPlaces VALUES ('92', '5', '4');
INSERT INTO LesPlaces VALUES ('92', '5', '5');
INSERT INTO LesPlaces VALUES ('93', '5', '1');
INSERT INTO LesPlaces VALUES ('93', '5', '2');
INSERT INTO LesPlaces VALUES ('93', '5', '3');
INSERT INTO LesPlaces VALUES ('93', '5', '4');
INSERT INTO LesPlaces VALUES ('93', '5', '5');
INSERT INTO LesPlaces VALUES ('94', '5', '1');
INSERT INTO LesPlaces VALUES ('94', '5', '2');
INSERT INTO LesPlaces VALUES ('94', '5', '3');
INSERT INTO LesPlaces VALUES ('94', '5', '4');
INSERT INTO LesPlaces VALUES ('94', '5', '5');
INSERT INTO LesPlaces VALUES ('95', '5', '1');
INSERT INTO LesPlaces VALUES ('95', '5', '2');
INSERT INTO LesPlaces VALUES ('95', '5', '3');
INSERT INTO LesPlaces VALUES ('95', '5', '4');
INSERT INTO LesPlaces VALUES ('95', '5', '5');
INSERT INTO LesPlaces VALUES ('96', '5', '1');
INSERT INTO LesPlaces VALUES ('96', '5', '2');
INSERT INTO LesPlaces VALUES ('96', '5', '3');
INSERT INTO LesPlaces VALUES ('96', '5', '4');
INSERT INTO LesPlaces VALUES ('96', '5', '5');
INSERT INTO LesPlaces VALUES ('97', '5', '1');
INSERT INTO LesPlaces VALUES ('97', '5', '2');
INSERT INTO LesPlaces VALUES ('97', '5', '3');
INSERT INTO LesPlaces VALUES ('97', '5', '4');
INSERT INTO LesPlaces VALUES ('97', '5', '5');
INSERT INTO LesPlaces VALUES ('98', '5', '1');
INSERT INTO LesPlaces VALUES ('98', '5', '2');
INSERT INTO LesPlaces VALUES ('98', '5', '3');
INSERT INTO LesPlaces VALUES ('98', '5', '4');
INSERT INTO LesPlaces VALUES ('98', '5', '5');
INSERT INTO LesPlaces VALUES ('99', '5', '1');
INSERT INTO LesPlaces VALUES ('99', '5', '2');
INSERT INTO LesPlaces VALUES ('99', '5', '3');
INSERT INTO LesPlaces VALUES ('99', '5', '4');
INSERT INTO LesPlaces VALUES ('99', '5', '5');


---------------------------------------------------------------------------
-- LesDossiers
---------------------------------------------------------------------------
INSERT INTO LesDossiers VALUES ('1');
INSERT INTO LesDossiers VALUES ('2');
INSERT INTO LesDossiers VALUES ('3');
INSERT INTO LesDossiers VALUES ('4');
INSERT INTO LesDossiers VALUES ('5');

---------------------------------------------------------------------------
-- LesRepresentations
---------------------------------------------------------------------------

INSERT INTO LesRepresentations VALUES ('2019-03-11 20:00:00', '1');
INSERT INTO LesRepresentations VALUES ('2019-03-11 22:00:00', '2');
INSERT INTO LesRepresentations VALUES ('2019-03-11 18:00:00', '3');
INSERT INTO LesRepresentations VALUES ('2019-03-12 18:00:00', '1');
INSERT INTO LesRepresentations VALUES ('2019-03-12 20:00:00' ,'2');
INSERT INTO LesRepresentations VALUES ('2019-03-12 22:00:00' ,'3');
INSERT INTO LesRepresentations VALUES ('2019-03-13 20:00:00', '1');
INSERT INTO LesRepresentations VALUES ('2019-03-13 22:00:00', '4');
INSERT INTO LesRepresentations VALUES ('2019-03-13 18:00:00', '5');
INSERT INTO LesRepresentations VALUES ('2019-03-14 18:00:00' ,'1');
INSERT INTO LesRepresentations VALUES ('2019-03-14 20:00:00', '4');
INSERT INTO LesRepresentations VALUES ('2019-03-14 22:00:00' ,'5');
INSERT INTO LesRepresentations VALUES ('2019-03-15 16:00:00' ,'1');
INSERT INTO LesRepresentations VALUES ('2019-03-15 18:00:00' ,'2');
INSERT INTO LesRepresentations VALUES ('2019-03-15 20:00:00', '3');
INSERT INTO LesRepresentations VALUES ('2019-03-15 22:00:00', '4');
INSERT INTO LesRepresentations VALUES ('2019-03-15 14:00:00' ,'5');

---------------------------------------------------------------------------
-- LesTickets
---------------------------------------------------------------------------

INSERT INTO LesTickets VALUES ('1','1', '1', '2019-03-11 20:00:00', '1', '20190310140000', '1');
INSERT INTO LesTickets VALUES ('2','2', '1', '2019-03-11 20:00:00', '1', '20190310140001', '1');
INSERT INTO LesTickets VALUES ('3','14', '3', '2019-03-11 20:00:00', '1', '20190301140000', '2');
INSERT INTO LesTickets VALUES ('4', '15', '3', '2019-03-11 20:00:00', '1', '20190301140001', '2');
INSERT INTO LesTickets VALUES ('5','77', '3', '2019-03-13 18:00:00', '5', '20190304140003', '3');
INSERT INTO LesTickets VALUES ('6','78', '3', '2019-03-13 18:00:00', '5', '20190304140004', '3');
INSERT INTO LesTickets VALUES ('7','79', '3', '2019-03-13 18:00:00', '5', '20190304140005', '3');
INSERT INTO LesTickets VALUES ('8','77', '3', '2019-03-14 20:00:00', '4', '20190222140003', '4');
INSERT INTO LesTickets VALUES ('9','16', '3', '2019-03-15 22:00:00', '4', '20190210140005', '5');
